# -*- coding: utf-8 -*-
"""Référentiel d'appréciation par métier : volumes de marché (stocks datés observés),
tension, accessibilité junior, exposition à l'automatisation, qualité du débouché.
Chaque appréciation est justifiée et tracée (OBSERVE / ESTIMATION)."""

# STOCK_INDEED : bornes basses observées dans les titres de pages de liste Indeed (compteurs datés).
# Ce sont des comptes de PERTINENCE par mots-clés, pas des comptes stricts d'intitulés :
# ils servent d'INDICATEURS RELATIFS entre métiers, jamais de nombre d'emplois disponibles.
REF = {
"Analyste SOC": dict(
  STOCK_NATIONAL="≥ 300 (28/05/2026, « Analyste Soc ») ; ≥ 400 « Cyber Security SOC Analyste » (14/08/2026) ; ≈ 329 « Analyste Cybersécurité » (20/03/2026) ; ≈ 231 « Analyste Cyber Security » (23/05/2026)",
  STOCK_PARIS="≥ 50 (Indeed, 29/06/2026, Paris 75) ; ≥ 50 SOC Analyst IdF (11/08/2026)",
  TENSION="EN_TENSION",
  TENSION_JUST="Stock national significatif et récurrent sur toute la période 2026 ; présence continue chez les MSSP/ESN (Sopra Steria, Atos, Capgemini, Advens, AlgoSecure, Itrust) et en interne (banque, public, industrie). Mais offres majoritairement N2/N3.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Dans notre corpus, la quasi-totalité des postes d'analyste SOC en CDI exigent N2/N3 ou 4-6 ans (Atos : Bac+5 + 4 ans ; Michael Page : Bac+3 + 5 ans ; Ivry : Bac+5 + 4 ans + certification SIEM/SOAR/EDR). Les entrées juniors passent par l'alternance et le stage (Advens Lille, IMS Networks Castres, CHANEL, apprenti analyste SOC junior Paris) ou par des postes N1 peu nombreux.",
  AUTOMATISATION="ELEVEE sur le N1, FAIBLE sur le N2/N3",
  AUTOMATISATION_JUST="Sources convergentes : JDN/CSB.School cite l'analyste SOC niveau 1 parmi les métiers rendus obsolètes par l'IA ; une analyse spécialisée avance 70-80 % des alertes N1 traitées par l'IA. Nos offres N1 pures sont quasi absentes du corpus (aucune offre CDI intitulée « analyste SOC N1 »), alors que les N2/N3 dominent.",
  QUALITE="FAVORABLE", SALAIRE="35-55 k€ selon niveau L1/L2/L3 (Scope Cyber 2026) ; 37,3-65 k€ affichés sur une offre SOC Detection (HelloWork)",
  ATTRACTIVITE_ETUDIANT="FORTE"),
"Detection Engineer / SOC Engineering": dict(
  STOCK_NATIONAL="NC en propre (intitulé peu utilisé dans les pages de liste indexées)",
  STOCK_PARIS="NC", TENSION="EN_TENSION",
  TENSION_JUST="Peu d'offres portant explicitement l'intitulé, mais la compétence est demandée à l'intérieur des offres SOC N2/N3 (règles de corrélation, playbooks SOAR, cas d'usage de détection) et fait l'objet de missions freelance dédiées (migration QRadar→Sentinel, log integrator/parsing).",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Une alternance explicitement « SOC Detection Engineer » observée (Advens, Lille, 2026) et une alternance Analyste SOC/risk (CHANEL) : la porte d'entrée existe mais reste étroite et adossée à un encadrement expert.",
  AUTOMATISATION="FAIBLE",
  AUTOMATISATION_JUST="C'est la compétence qui capte la valeur libérée par l'automatisation du N1 : concevoir, régler et superviser les règles et playbooks que l'IA exécute.",
  QUALITE="TRES_FAVORABLE", SALAIRE="NC en propre ; positionné au-dessus de l'analyste SOC N2",
  ATTRACTIVITE_ETUDIANT="MOYENNE"),
"SecOps / Security Operations Engineer": dict(
  STOCK_NATIONAL="NC en propre", STOCK_PARIS="NC", TENSION="EN_TENSION",
  TENSION_JUST="Postes observés chez des grands comptes et ESN (Nanterre, Bordeaux, TDS Global, missions freelance Hauts-de-France exigeant 7-10 ans SOC/SecOps/IR).",
  ACCESSIBILITE="DIFFICILE",
  ACCESSIBILITE_JUST="Les offres SecOps observées demandent une expérience opérationnelle confirmée (souvent 5 ans et plus) ; aucune offre junior identifiée hors alternance.",
  AUTOMATISATION="FAIBLE", AUTOMATISATION_JUST="Métier d'industrialisation et d'automatisation : l'IA en augmente la valeur.",
  QUALITE="TRES_FAVORABLE", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="MOYENNE"),
"Analyste DFIR / Incident Response": dict(
  STOCK_NATIONAL="NC en propre ; « Threat Hunting » ≥ 50 (21/07/2026)", STOCK_PARIS="NC",
  TENSION="EN_TENSION",
  TENSION_JUST="Volume faible mais structurellement rare : CERT/CSIRT internes (Crédit Mutuel, XMCO) et prestataires spécialisés.",
  ACCESSIBILITE="TRES_DIFFICILE",
  ACCESSIBILITE_JUST="Aucune offre junior DFIR observée ; les postes exigent une expertise forensic/malware confirmée (analyste DFIR/CTI senior, DFIR incident response).",
  AUTOMATISATION="FAIBLE", AUTOMATISATION_JUST="Investigation complexe, raisonnement adversarial, non répétitive.",
  QUALITE="MOYEN", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FORTE"),
"Analyste Threat Intelligence / Threat Hunter": dict(
  STOCK_NATIONAL="≥ 100 « Threat Intelligence » (16/07/2026) ; ≥ 50 « Threat Hunting » (21/07/2026)",
  STOCK_PARIS="≥ 25 « Cyber Threat Intelligence » (20/05/2026)", TENSION="EQUILIBRE",
  TENSION_JUST="Stock national modeste et stable ; postes concentrés chez les MSSP (Sopra Steria), les grands industriels (Thales) et quelques spécialistes (OWN, XMCO).",
  ACCESSIBILITE="DIFFICILE",
  ACCESSIBILITE_JUST="Les offres CTI observées demandent 3 à 7 ans (Sopra Steria) ou une première expérience réussie en SOC/CSIRT (Thales). Deux portes juniors observées : apprenti analyste de la menace (ANSSI) et stage CTI (Sopra Steria).",
  AUTOMATISATION="MOYENNE",
  AUTOMATISATION_JUST="La collecte, l'enrichissement d'IOC et la veille OSINT de premier niveau sont automatisables ; l'analyse de campagnes et l'attribution ne le sont pas.",
  QUALITE="MOYEN", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FORTE"),
"Pentester / Consultant sécurité offensive": dict(
  STOCK_NATIONAL="≥ 25 « Pentester » (extrait : 33) au 28/08/2026 ; 31 « penetration testing » (Glassdoor, 05/2026). Local : 4 à 6 à Lyon (20 et 22/07/2026). Ordre de grandeur indépendant : ≈ 150 recrutements de pentesters en France en 2025 contre ≈ 120 en 2024 (Mercato de l'Emploi)",
  STOCK_PARIS="page datée sans compte (11/08/2026)", TENSION="EQUILIBRE",
  TENSION_JUST="Écart majeur entre notoriété et volume : ~33 offres « pentester » au niveau national contre ≥ 300 « analyste SOC », ≥ 800 « DevSecOps » et ≥ 700 « IAM ». Le marché existe mais il est étroit et concentré sur quelques cabinets (Synacktiv, Deloitte, XMCO, AlgoSecure) et quelques équipes internes.",
  ACCESSIBILITE="TRES_DIFFICILE",
  ACCESSIBILITE_JUST="Synacktiv exige 3 ans minimum d'expérience offensive et la maîtrise complète de la chaîne (AD, cloud, CI/CD) ; Deloitte exige une expérience de pentest démontrée. Aucune alternance pentest « pure » dans notre corpus : les seules portes juniors observées sont des stages de recherche (Thales THALIUM, Framatome) et des alternances mixtes (Schneider Electric : DevSecOps + tests d'intrusion).",
  AUTOMATISATION="MOYENNE",
  AUTOMATISATION_JUST="Le scan et la reconnaissance sont largement outillés ; l'exploitation créative et le Red Team ne le sont pas. Le JDN cite explicitement le red teamer parmi les métiers qui « séduisent mais ne recrutent plus ».",
  QUALITE="FRAGILE",
  SALAIRE="45-80 k€ (Scope Cyber 2026) ; TJM senior 600-900 €/j ; +15 à 30 % vs analyste SOC en freelance (Silkhom)",
  ATTRACTIVITE_ETUDIANT="TRES_FORTE"),
"Analyste / Manager Vulnérabilités (VOC)": dict(
  STOCK_NATIONAL="≥ 100 « Vulnerability Management » (extrait : 153) au 15/06/2026 ; ≥ 50 « VM Lead » (21/07/2026)",
  STOCK_PARIS="NC", TENSION="EN_TENSION",
  TENSION_JUST="Fonction en structuration (apparition des « VOC » — Vulnerability Operation Center — chez Crédit Mutuel/Euro-Information, Sopra Steria, Urssaf) ; employeurs cités : Safran, EQUANS, Orange Cyberdefense, AXA, Ingenico.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Postes CDI demandant typiquement 5 ans, mais portes juniors réelles observées : stage analyste VOC (Sopra Steria ×2), alternance évaluation vulnérabilités (Schneider Electric), analyste VOC Bac+3 + première expérience (Crédit Mutuel Arkéa).",
  AUTOMATISATION="MOYENNE-ELEVEE",
  AUTOMATISATION_JUST="Le scan, la priorisation par score et la génération de recommandations standard sont massivement outillés ; la négociation de la remédiation avec les équipes IT/métier ne l'est pas.",
  QUALITE="FAVORABLE", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Cloud Security Engineer / Architect": dict(
  STOCK_NATIONAL="≥ 400 « Cloud Security Engineer » (extrait : 438) au 25/05/2026 ; ≥ 1 000 « Cloud Security » (extrait : 1 324) au 08/09/2026. Local : ≈ 69 « Cyber Sécurité Cloud » à Lyon (18/06/2026), ≥ 25 à Nantes (06/09/2024)",
  STOCK_PARIS="≥ 200 « Cloud Security Engineer » (extrait : 273) au 26/05/2026 ; ≥ 700 « Cloud Security » Paris (extrait : 769) au 01/09/2026",
  TENSION="TRES_EN_TENSION",
  TENSION_JUST="Un des stocks les plus élevés du périmètre, stable de janvier à septembre 2026 (≥ 600 « Ingénieur Sécurité Cloud » IdF au 06/01/2026, ≥ 769 « Cloud Security » Paris au 01/09/2026). Compétence transverse présente dans une large part des offres d'architecture, DevSecOps, IAM et généralistes.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Peu de postes cloud security « juniors » en propre, mais la compétence cloud est demandée dès l'alternance (MONEXT : Sentinel, Intune, Azure AD, Defender ; France Travail Bordeaux : SI, réseaux et cloud) et un stage/alternance dédié « Cloud et sécurité » a été observé. Prérequis : systèmes, réseaux et IaC.",
  AUTOMATISATION="FAIBLE",
  AUTOMATISATION_JUST="Conception d'architectures et arbitrages de configuration : l'IA accélère l'audit de posture, pas la décision d'architecture.",
  QUALITE="TRES_FAVORABLE",
  SALAIRE="Non affiché dans nos offres ; les baromètres 2026 placent le Cloud Security parmi les spécialités dont la valeur augmente le plus",
  ATTRACTIVITE_ETUDIANT="MOYENNE",
  RESERVE="Un article du Journal du Net (CSB.School) affirme au contraire que le Cloud Security connaîtrait des difficultés du fait d'un retour vers l'on-premise. Cette affirmation isolée est CONTREDITE par nos relevés de stocks (400-769 offres selon la requête, stables sur 8 mois) et n'est étayée par aucune donnée dans la source."),
"DevSecOps Engineer": dict(
  STOCK_NATIONAL="≥ 800 « DevSecOps » (extrait : 817) au 04/09/2026 ; ≥ 700 au 15/04/2026. Local : ≈ 52 à Lyon (06/09/2026), ≈ 43 à Toulouse (03/03/2026)",
  STOCK_PARIS="≥ 300 (extrait : 330) au 15/04/2026 ; ≥ 200 « DevSecOps Engineer » (extrait : 248) au 28/08/2026",
  TENSION="TRES_EN_TENSION",
  TENSION_JUST="Le stock le plus élevé de toutes les spécialités cyber observées, en progression entre avril (≥ 700) et septembre 2026 (≥ 800). Présent dans tous les secteurs observés : banque, santé, industrie, éditeurs, ESN.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Portes juniors réelles et documentées : « Ingénieur DevSecOps Junior » (France Travail, Toulouse, avec description de poste junior explicite : pipelines SAST/SCA/DAST, SBOM, templates CI/CD), alternance DevSecOps (Padoa), ≥ 25 stages DevSecOps (Indeed, 01/06/2026), 21 alternances DevSecOps en IdF (24/05/2026). MAIS le prérequis est un socle développement + CI/CD + conteneurs que les cursus cyber généralistes ne donnent pas.",
  AUTOMATISATION="FAIBLE",
  AUTOMATISATION_JUST="Métier dont l'objet même est l'automatisation ; les copilotes de code augmentent la productivité sans supprimer le rôle.",
  QUALITE="TRES_FAVORABLE", SALAIRE="NC dans nos offres",
  ATTRACTIVITE_ETUDIANT="MOYENNE",
  RESERVE="Le Journal du Net cite les « ingénieurs DevSec spécialisés » parmi les postes rendus obsolètes par l'IA. Cette affirmation est CONTREDITE par le stock observé (≥ 817 au 04/09/2026, en hausse sur l'année)."),
"AppSec / Product Security Engineer": dict(
  STOCK_NATIONAL="≥ 600 « Application Security Engineer » (10/08/2026) ; ≈ 1 142 « Sécurité applicative » (04/02/2026) ; ≥ 400 « Ingénieur Sécurité Applicative » (23/05/2026)",
  STOCK_PARIS="≥ 300 « Application Security Engineer » (extrait : 354) au 17/08/2026",
  TENSION="TRES_EN_TENSION",
  TENSION_JUST="Stock élevé, employeurs très diversifiés : grands groupes (Safran, banque), conseil (Accenture), éditeurs et scale-ups (GitGuardian, Akeneo, Tiime, Yousign, Scaleway, Mistral AI).",
  ACCESSIBILITE="DIFFICILE",
  ACCESSIBILITE_JUST="Les offres AppSec exigent une compréhension réelle du code : Akeneo demande 2-5 ans de sécurité en environnement web, Tiime 4-6 ans, Safran un accompagnement des équipes produit. Le poste « Application Security Manager » (Bordeaux) exige la maîtrise de SAST/DAST/SCA/API/conteneurs et du threat modeling. Aucune alternance AppSec pure dans notre corpus.",
  AUTOMATISATION="FAIBLE-MOYENNE",
  AUTOMATISATION_JUST="Le scan de code est outillé et l'IA génère des correctifs ; l'arbitrage de risque applicatif et le threat modeling restent humains.",
  QUALITE="TRES_FAVORABLE", SALAIRE="NC dans nos offres", ATTRACTIVITE_ETUDIANT="MOYENNE"),
"Consultant / Ingénieur IAM - PAM": dict(
  STOCK_NATIONAL="≥ 700 « IAM » (extrait : 732) au 31/03/2026 ; ≈ 405 « Identity Access Management » (18/07/2025) et 399 sur Glassdoor (09/2025). Local : ≈ 35 à Nantes (04/05/2026)",
  STOCK_PARIS="≥ 300 « Identity Access Management » (extrait : 360) au 26/05/2026",
  TENSION="TRES_EN_TENSION",
  TENSION_JUST="Stock élevé et durable ; l'IAM apparaît en outre comme compétence dans les offres d'architecture, de cloud et de réseau (Zero Trust, SASE, Entra ID). Recruteurs : ESN et cabinets (Sopra Steria, Capgemini, Deloitte, CGI, Eviden), éditeurs (Memority), grands comptes (EDF).",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Seuils d'entrée relativement bas pour une spécialité technique : Deloitte 2 ans, Aix-en-Provence Bac+4/5 + 1 an, et une alternance IAM explicite observée (Montrouge, septembre 2026). C'est, avec le GRC, la spécialisation technique la plus atteignable après un premier poste.",
  AUTOMATISATION="FAIBLE",
  AUTOMATISATION_JUST="Le provisioning est automatisé depuis longtemps ; la gouvernance des identités, les campagnes de revue et l'intégration applicative restent des projets humains.",
  QUALITE="TRES_FAVORABLE", SALAIRE="NC dans nos offres", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Consultant GRC / Risque / Conformité": dict(
  STOCK_NATIONAL="≥ 200 « Cybersécurité GRC » (extrait : 242) au 03/09/2026 ; ≥ 300 « ISO 27001 » à Paris (21/10/2025). Local : ≈ 14 à Lyon (03/01/2026)",
  STOCK_PARIS="≥ 100 (extrait : 112) au 03/09/2026 ; ≥ 75 IdF (extrait : 92) au 11/08/2026",
  TENSION="EN_TENSION",
  TENSION_JUST="Stock en progression et surtout forte cohérence avec le calendrier réglementaire : NIS2 (10 000 à 15 000 organisations supplémentaires concernées), DORA, Cyber Resilience Act à partir de juin 2026. Nos offres GRC citent massivement ISO 27001, EBIOS RM, NIS2, DORA, HDS, SOC 2.",
  ACCESSIBILITE="ACCESSIBLE",
  ACCESSIBILITE_JUST="C'est la famille la plus ouverte aux profils en formation dans notre corpus : 12 alternances GRC identifiées (MGEN, Safran, Thales Bordeaux, Framatome/EDF Grenoble, Onet Marseille, PSTB, Icademie, Lyon...) et des seuils d'entrée CDI plus bas (Upcoop 3-5 ans, Toulouse 3-5 ans, CyberTee 4 ans). Attention : les postes « confirmés » restent majoritaires.",
  AUTOMATISATION="MOYENNE",
  AUTOMATISATION_JUST="Rédaction documentaire, questionnaires fournisseurs, cartographies et reporting sont fortement accélérés par l'IA générative ; l'analyse de risque contextualisée et la relation avec les métiers ne le sont pas.",
  QUALITE="FAVORABLE", SALAIRE="NC dans nos offres", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Auditeur cybersécurité / SSI": dict(
  STOCK_NATIONAL="NC en propre", STOCK_PARIS="NC", TENSION="EN_TENSION",
  TENSION_JUST="Fonction portée par le même moteur réglementaire que le GRC ; observée chez l'Urssaf (Nantes), en cabinet et en interne.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="L'offre d'auditeur cyber de l'Urssaf demande Bac+5 ou 5 ans d'expérience, avec exposition pentest et gestion des vulnérabilités.",
  AUTOMATISATION="MOYENNE", AUTOMATISATION_JUST="Collecte de preuves et rédaction de rapports accélérées par l'IA.",
  QUALITE="FAVORABLE", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Architecte sécurité / cybersécurité": dict(
  STOCK_NATIONAL="≥ 400 « Security Architect » (11/06/2026) ; ≈ 455 « Cybersecurity Architect » (22/06/2026) ; 404 (Glassdoor, 07/2026). Ordre de grandeur indépendant : ≈ 400 recrutements d'architectes cyber en France en 2025 contre ≈ 350 en 2024 (Mercato de l'Emploi)",
  STOCK_PARIS="≥ 200 (extrait : 277) au 18/08/2026 ; 270 (Glassdoor, août 2026)",
  TENSION="TRES_EN_TENSION",
  TENSION_JUST="Cohérent avec l'Observatoire ANSSI : les architectes représentent 21 % des offres analysées (premier métier du corpus, 23 000 offres). Deux sources indépendantes (Indeed et Glassdoor) donnent des ordres de grandeur voisins (≈ 400 France, ≈ 270-277 Paris).",
  ACCESSIBILITE="TRES_DIFFICILE",
  ACCESSIBILITE_JUST="Safran exige Bac+5 + 5 ans, l'architecte Sécurité & Réseau Cloud (France Travail) 7-8 ans. C'est un métier de destination à 8-10 ans, pas un débouché de sortie d'école — alors qu'il constitue le premier volume du marché.",
  AUTOMATISATION="TRES_FAIBLE", AUTOMATISATION_JUST="Conception, arbitrage et responsabilité : le cœur non automatisable.",
  QUALITE="TRES_FAVORABLE (à moyen terme, pas en sortie d'école)", SALAIRE="NC dans nos offres",
  ATTRACTIVITE_ETUDIANT="MOYENNE"),
"Ingénieur sécurité réseau / infrastructure": dict(
  STOCK_NATIONAL="≥ 1 000 « Ingénieur Réseau Sécurité » (extrait : 1 736) au 04/08/2026 — requête large ; ≥ 600 « Ingénieur Réseaux Cyber Sécurité » (25/07/2026)",
  STOCK_PARIS="≥ 600 IdF (extrait : 684) au 28/05/2026",
  TENSION="EN_TENSION",
  TENSION_JUST="Volumes élevés mais requêtes très larges (recouvrement fort avec l'administration système et réseau non cyber) : à lire comme une borne haute et non comme un volume cyber pur.",
  ACCESSIBILITE="ACCESSIBLE",
  ACCESSIBILITE_JUST="C'est la porte d'entrée la plus large observée : alternances systèmes-réseaux-sécurité nombreuses (Sopra Steria Villeneuve-d'Ascq, Metz, Aubière Bac+3/4, Bordeaux, Sarcelles), postes de technicien/administrateur sécurité accessibles à Bac+2/+3.",
  AUTOMATISATION="MOYENNE", AUTOMATISATION_JUST="Configuration et supervision partiellement automatisées ; le diagnostic réseau reste humain.",
  QUALITE="FAVORABLE",
  SALAIRE="NC dans nos offres", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Ingénieur / Consultant sécurité OT-ICS": dict(
  STOCK_NATIONAL="≥ 50 « OT Security » (extrait : 54) au 19/05/2026", STOCK_PARIS="NC",
  TENSION="EN_TENSION",
  TENSION_JUST="Volume national faible mais demande qualifiée et durable, portée par NIS2, la LPM et IEC 62443 ; forte présence en régions industrielles (Belfort, Grenoble, Lyon, Toulouse, Bouzonville, Montreuil-Juigné).",
  ACCESSIBILITE="DIFFICILE",
  ACCESSIBILITE_JUST="Les offres exigent 5 à 8 ans et une culture industrielle (SCADA, DCS, PLC). Portes juniors observées : alternance sécurité des systèmes industriels (ZF, Bouzonville), stage détection comportementale industrielle (Framatome, Lyon), alternance Framatome Montreuil-Juigné.",
  AUTOMATISATION="FAIBLE", AUTOMATISATION_JUST="Environnements propriétaires et contraintes de sûreté : peu automatisable.",
  QUALITE="FAVORABLE (en régions industrielles)", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="MOYENNE"),
"AI Security / LLM Security Engineer": dict(
  STOCK_NATIONAL="Aucun compteur dédié observé sur les jobboards français. Un cabinet de recrutement avance 119 offres « Red Team » sur LinkedIn France en mai 2026 (non vérifiable, non spécifique AI Security).",
  STOCK_PARIS="NC", TENSION="DONNEES_INSUFFISANTES",
  TENSION_JUST="Aucune source française fiable ne permet de mesurer un stock d'offres « AI Security ». Nos 6 offres relevant de ce champ sont pour l'essentiel des postes existants auxquels s'ajoute une dimension IA (pentester IA chez Cybermaker, architecte sécurité cloud/DevSecOps/IA, ingénieur sécurité système avec IA appliquée à l'analyse cyber, software engineer AI agent pour équipes sécurité), plus des postes IA/data intégrant sécurité et gouvernance.",
  ACCESSIBILITE="DONNEES_INSUFFISANTES",
  ACCESSIBILITE_JUST="Une seule alternance identifiée (« Ingénieur Développement cybersécurité IA », Vélizy). Aucun marché junior observable.",
  AUTOMATISATION="SANS_OBJET", AUTOMATISATION_JUST="Métier créé par l'IA elle-même.",
  QUALITE="DONNEES_INSUFFISANTES",
  SALAIRE="65-180 k€ et TJM 700-1 400 €/j selon un cabinet de recrutement (Get in Talent) — ESTIMATION non vérifiable, à ne pas utiliser comme référence",
  ATTRACTIVITE_ETUDIANT="TRES_FORTE",
  RESERVE="Conclusion : compétence émergente réelle et stratégique, mais AUCUN marché autonome mesurable en France en 2026. Ne peut pas fonder une spécialisation entière."),
"RSSI / CISO / Responsable cybersécurité": dict(
  STOCK_NATIONAL="≥ 400 « RSSI, CISO » (03/09/2026) ; 52 « information systems security officer » (Glassdoor, juin 2026)",
  STOCK_PARIS="NC", TENSION="EN_TENSION",
  TENSION_JUST="Le RSSI est le métier le plus représenté parmi les professionnels cyber (30 %, Observatoire ANSSI 2025) ; forte demande, y compris RSSI externalisé et RSSI de filiale.",
  ACCESSIBILITE="TRES_DIFFICILE",
  ACCESSIBILITE_JUST="8 ans (Unibail), expérience confirmée de RSSI exigée (Nanterre) : trajectoire de carrière, jamais un débouché de sortie d'école.",
  AUTOMATISATION="TRES_FAIBLE", AUTOMATISATION_JUST="Responsabilité, arbitrage et représentation.",
  QUALITE="TRES_FAVORABLE (destination de carrière)", SALAIRE="70-220 k€ (Scope Cyber 2026)",
  ATTRACTIVITE_ETUDIANT="MOYENNE"),
"Chef de projet cybersécurité": dict(
  STOCK_NATIONAL="NC en propre", STOCK_PARIS="NC", TENSION="EQUILIBRE",
  TENSION_JUST="Présence régulière mais diffuse (assurance, banque, industrie, IAM, GRC).",
  ACCESSIBILITE="DIFFICILE",
  ACCESSIBILITE_JUST="Suppose une légitimité technique préalable ; quelques alternances (Onet Technologies, Savencia).",
  AUTOMATISATION="MOYENNE", AUTOMATISATION_JUST="Reporting et documentation projet fortement accélérés par l'IA.",
  QUALITE="MOYEN", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Ingénieur cybersécurité (généraliste)": dict(
  STOCK_NATIONAL="≥ 1 000 « Ingénieur Cybersécurité » (07/09/2026) ; ≥ 1 000 « Ingénieur Cyber Sécurité » (20/08/2026)",
  STOCK_PARIS="≥ 600 (07/09/2026)", TENSION="EN_TENSION",
  TENSION_JUST="Premier stock du périmètre en valeur brute, mais intitulé « parapluie » : derrière « ingénieur cybersécurité » nos offres recouvrent en réalité du SOC, du réseau, du cloud, de l'IAM, de l'OT et de la conformité. Le volume mesure la popularité de l'intitulé, pas l'existence d'un métier généraliste homogène.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="≥ 300 « Cybersécurité Junior » (02/09/2026) et ≥ 100 « Débutant Cybersécurité » (01/09/2026) mais seulement ≥ 25 « Débutant Cybersécurité » en IdF (extrait : 26) au 04/09/2026 — soit environ 1 % du stock cyber francilien (≈ 2 444 offres). L'écart entre le stock global et le stock réellement ouvert aux débutants est le résultat le plus important de cette étude.",
  AUTOMATISATION="MOYENNE",
  AUTOMATISATION_JUST="Les tâches de premier niveau (tri d'alertes, reporting, enrichissement, recommandations standard) sont les plus exposées ; c'est précisément le contenu d'un poste généraliste junior.",
  QUALITE="MOYEN",
  SALAIRE="42-48 k€ pour un profil junior selon Cyberini 2026 (ESTIMATION)",
  ATTRACTIVITE_ETUDIANT="FORTE",
  RESERVE="Les baromètres 2026 signalent une stagnation salariale des profils généralistes face à la valorisation des experts Cloud, IA défensive et conformité."),
"Consultant cybersécurité (généraliste)": dict(
  STOCK_NATIONAL="≥ 800 « Consultant Cybersécurité » (extrait : 802) au 02/09/2026 ; ≥ 600 « Consultant Junior Cyber Sécurité » (02/09/2026)",
  STOCK_PARIS="≥ 200 (extrait : 286) au 18/05/2026", TENSION="EN_TENSION",
  TENSION_JUST="Deuxième métier de l'Observatoire ANSSI (15 % des offres). Porté par les ESN, MSSP et cabinets, qui recrutent en volume et forment en interne.",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="≥ 50 « Consultant Cybersécurité Junior » (extrait : 66) au 19/03/2026 : le junior existe, principalement en cabinet et en ESN, avec un parcours d'intégration (AlgoSecure : 2-3 semaines d'intégration puis mission client). C'est la voie d'entrée la plus fréquente pour un diplômé.",
  AUTOMATISATION="MOYENNE", AUTOMATISATION_JUST="Production documentaire et livrables standard accélérés par l'IA.",
  QUALITE="FAVORABLE", SALAIRE="NC dans nos offres", ATTRACTIVITE_ETUDIANT="MOYENNE"),
"Analyste cybersécurité (généraliste)": dict(
  STOCK_NATIONAL="≥ 300 « Analyste Cyber Security » (31/08/2026)", STOCK_PARIS="NC",
  TENSION="EQUILIBRE",
  TENSION_JUST="Intitulé fréquent mais recouvrant des réalités hétérogènes (SOC, VOC, risques, menaces).",
  ACCESSIBILITE="ACCESSIBLE_AVEC_PRE_REQUIS",
  ACCESSIBILITE_JUST="Plusieurs offres Bac+3 + première expérience (Crédit Mutuel Arkéa) et de nombreuses alternances « analyste cybersécurité ».",
  AUTOMATISATION="ELEVEE",
  AUTOMATISATION_JUST="Le cœur du poste junior (tri, qualification, enrichissement, reporting) est le plus directement visé par l'automatisation et les copilotes de sécurité.",
  QUALITE="MOYEN", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FORTE"),
"Administrateur / technicien sécurité": dict(
  STOCK_NATIONAL="≥ 700 « Administrateur Sécurité Informatique » (extrait : 744) au 25/08/2026 — requête large ; ≥ 50 « Administrateur Cyber Sécurité » (05/02/2026)",
  STOCK_PARIS="NC", TENSION="EQUILIBRE",
  TENSION_JUST="Requête large, fort recouvrement avec l'administration système non cyber.",
  ACCESSIBILITE="ACCESSIBLE",
  ACCESSIBILITE_JUST="Niveau Bac+2/+3 fréquemment suffisant ; nombreuses alternances support IT / systèmes-réseaux avec volet cybersécurité.",
  AUTOMATISATION="ELEVEE",
  AUTOMATISATION_JUST="Tâches d'exploitation répétitives, fortement outillées.",
  QUALITE="MOYEN", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="FAIBLE"),
"Métier adjacent (DevOps / Cloud / Data / IA sans mission sécurité explicite)": dict(
  STOCK_NATIONAL="≥ 2 000 « Cloud Engineer » (07/09/2026) — hors périmètre cyber strict",
  STOCK_PARIS="NC", TENSION="DONNEES_INSUFFISANTES",
  TENSION_JUST="Hors périmètre : conservés pour mesurer la porosité entre cyber, DevOps et cloud.",
  ACCESSIBILITE="DONNEES_INSUFFISANTES", ACCESSIBILITE_JUST="Hors périmètre.",
  AUTOMATISATION="NC", AUTOMATISATION_JUST="Hors périmètre.",
  QUALITE="DONNEES_INSUFFISANTES", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="MOYENNE"),
}

DEFAUT = dict(STOCK_NATIONAL="NC", STOCK_PARIS="NC", TENSION="DONNEES_INSUFFISANTES",
  TENSION_JUST="Volume observé insuffisant.", ACCESSIBILITE="DONNEES_INSUFFISANTES",
  ACCESSIBILITE_JUST="Volume observé insuffisant.", AUTOMATISATION="NC", AUTOMATISATION_JUST="NC",
  QUALITE="DONNEES_INSUFFISANTES", SALAIRE="NC", ATTRACTIVITE_ETUDIANT="NC")

def ref(metier):
    r = dict(DEFAUT); r.update(REF.get(metier, {})); return r
